# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vY8HHli0vBeMHk55tPW6pvxbIsBCBSH
"""

# Commented out IPython magic to ensure Python compatibility.
# # ============================
# # INSTALL DEPENDENCIES
# # ============================
# !pip install streamlit pyngrok transformers sentencepiece accelerate pypdf -q
# 
# # ============================
# # SETUP NGROK AUTH TOKEN
# # ============================
# NGROK_TOKEN = "YOUR_NGROK_TOKEN_HERE"   # <-- PUT YOUR TOKEN
# !ngrok config add-authtoken $NGROK_TOKEN
# 
# # ============================
# # CREATE FOLDERS
# # ============================
# !mkdir -p pages
# 
# 
# # ============================
# # CREATE llm.py (MAIN LLM FILE)
# # ============================
# %%writefile llm.py
# from transformers import AutoTokenizer, AutoModelForCausalLM
# 
# # Load Granite model
# tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
# model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
# 
# def ask_llm(prompt):
#     messages = [{"role": "user", "content": prompt}]
#     inputs = tokenizer.apply_chat_template(
#         messages,
#         add_generation_prompt=True,
#         tokenize=True,
#         return_dict=True,
#         return_tensors="pt",
#     ).to(model.device)
# 
#     outputs = model.generate(**inputs, max_new_tokens=300)
#     return tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:])
# 
# 
# # ============================
# # MAIN STREAMLIT HOME PAGE
# # ============================
# %%writefile main_app.py
# import streamlit as st
# 
# st.title("🎓 studyMate — AI Academic Assistant")
# 
# st.write("""
# Welcome to **studyMate**, your AI-powered learning companion.
# 
# ### ⭐ Features
# - **AI Tutor** — Ask questions from your PDFs
# - **Smart Notes** — Generate summaries
# - **Personalized Lessons** — Tailored study plans
# - **Interactive Quizzes** — Auto-generated quizzes
# """)
# 
# st.sidebar.success("Choose a page above.")
# 
# 
# # ============================
# # PAGE 1 — AI TUTOR
# # ============================
# %%writefile pages/1_AI_Tutor.py
# import streamlit as st
# from pypdf import PdfReader
# from llm import ask_llm
# 
# st.title("📘 AI Tutor")
# 
# uploaded_files = st.file_uploader("Upload PDFs", type="pdf", accept_multiple_files=True)
# 
# if uploaded_files:
#     text = ""
#     for f in uploaded_files:
#         reader = PdfReader(f)
#         for p in reader.pages:
#             text += p.extract_text() + "\n"
# 
#     question = st.text_input("Ask a question about your PDFs:")
# 
#     if st.button("Get Answer"):
#         with st.spinner("Thinking..."):
#             result = ask_llm(f"Answer the question using this text:\n{text}\n\nQuestion: {question}")
#             st.write(result)
# 
# 
# # ============================
# # PAGE 2 — SMART NOTES
# # ============================
# %%writefile pages/2_Smart_Notes.py
# import streamlit as st
# from pypdf import PdfReader
# from llm import ask_llm
# 
# st.title("📝 Smart Notes Generator")
# 
# file = st.file_uploader("Upload a PDF", type="pdf")
# 
# if file:
#     text = ""
#     reader = PdfReader(file)
#     for p in reader.pages:
#         text += p.extract_text() + "\n"
# 
#     if st.button("Summarize"):
#         with st.spinner("Summarizing..."):
#             summary = ask_llm(f"Summarize this text:\n{text}")
#             st.write(summary)
# 
# 
# # ============================
# # PAGE 3 — PERSONALIZED LESSONS
# # ============================
# %%writefile pages/3_Personalized_Lessons.py
# import streamlit as st
# from llm import ask_llm
# 
# st.title("🎯 Personalized Lessons")
# 
# topic = st.text_input("Enter topic:")
# level = st.selectbox("Your level:", ["Beginner", "Intermediate", "Advanced"])
# 
# if st.button("Generate Lesson"):
#     with st.spinner("Creating..."):
#         lesson = ask_llm(f"Create a {level} level lesson on: {topic}")
#         st.write(lesson)
# 
# 
# # ============================
# # PAGE 4 — QUIZ GENERATOR
# # ============================
# %%writefile pages/4_Interactive_Quizzes.py
# import streamlit as st
# from llm import ask_llm
# 
# st.title("🧠 Quiz Generator")
# 
# subject = st.text_input("Subject or chapter:")
# num_q = st.slider("Number of questions:", 3, 20, 5)
# 
# if st.button("Generate Quiz"):
#     with st.spinner("Creating quiz..."):
#         quiz = ask_llm(f"Create a {num_q}-question quiz on: {subject}. Include answers.")
#         st.write(quiz)
# 
# 
# # ============================
# # RUN STREAMLIT
# # ============================
# from pyngrok import ngrok
# 
# public_url = ngrok.connect(8501)
# print("🚀 Your App URL:", public_url)
# 
# !streamlit run main_app.py --server.port 8501 --server.headless true
# 
# 
#